import argparse
import sys

import pandas as pd

from yelp_review_intelligence.config import ProjectConfig
from yelp_review_intelligence.exceptions import IntelligenceGenerationError
from yelp_review_intelligence.intelligence import ReviewIntelligenceGenerator
from yelp_review_intelligence.logger import setup_logger
from yelp_review_intelligence.utils import save_json


logger = setup_logger(__name__)


def parse_args():
    """
    Parse command-line arguments.
    Allows selecting a configuration file and an optional business ID.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/config.yaml")
    parser.add_argument("--business-id", default=None)
    return parser.parse_args()


def main() -> None:
    """
    End-to-end pipeline for generating business-facing review intelligence.

    Steps:
    1. Load configuration.
    2. Load model predictions.
    3. Generate topic-level analysis.
    4. Generate business insights.
    5. Create dashboard-ready outputs.
    6. Save all generated artifacts.
    """
    try:
        # Read command-line arguments
        args = parse_args()

        logger.info("Starting intelligence output generation.")
        logger.info("Using config file: %s", args.config)

        # Load project configuration
        config = ProjectConfig.from_yaml(args.config)

        # Load predictions generated by the trained NLP model
        predictions_path = config.processed_dir / "test_predictions.pkl"
        logger.info("Loading predictions from %s", predictions_path)

        predictions_df = pd.read_pickle(predictions_path)

        # Initialize the business intelligence generator
        generator = ReviewIntelligenceGenerator(config)

        # Aggregate predictions into business topics
        topic_level_df = generator.create_topic_level_df(predictions_df)

        # Generate high-level business insights
        business_insights = generator.create_business_insights(topic_level_df)

        # Create dashboard-ready outputs
        dashboard_output, overall_sentiment, topic_summary, representative_reviews = (
            generator.create_dashboard_output(
                predictions_df,
                topic_level_df,
                business_id=args.business_id,
            )
        )

        # Save intermediate dataset
        topic_level_df.to_pickle(
            config.processed_dir / "topic_level_predictions.pkl"
        )

        # Save business insight reports
        business_insights.to_csv(
            config.output_dir / "business_topic_insights.csv",
            index=False,
        )

        overall_sentiment.to_csv(
            config.output_dir / "overall_sentiment_example_business.csv",
            index=False,
        )

        topic_summary.to_csv(
            config.output_dir / "topic_summary_example_business.csv",
            index=False,
        )

        representative_reviews.to_csv(
            config.output_dir / "representative_reviews_example_business.csv",
            index=False,
        )

        # Save final dashboard response as JSON
        save_json(
            dashboard_output,
            config.output_dir / "dashboard_output_example_business.json",
        )

        logger.info("Dashboard output generated successfully.")
        logger.info("Number of topic-level rows: %s", len(topic_level_df))
        logger.info("Number of business insight rows: %s", len(business_insights))

    except Exception as exc:
        # Log the full exception and raise a custom project exception
        logger.exception("Intelligence output generation failed.")
        raise IntelligenceGenerationError(
            "Intelligence output generation failed."
        ) from exc


if __name__ == "__main__":
    try:
        # Execute the pipeline
        main()
    except IntelligenceGenerationError:
        # Exit with a non-zero status code if the pipeline fails
        sys.exit(1)